language: python
python:
- "3.5"
env:
- TOXENV=py35
- TOXENV=pep8
before_install:
- pip install -U coveralls pip pytest pytest-cov setuptools wheel tox
script:
- tox
after_success:
- coveralls
notifications:
  slack:
    secure: Bu3p+D/fCUgKWNy3U0tggUGdlC8FyVplsBo8A6oCPOHZsdQ0jET+EjBBW0+ISVBsFAN1al50TqxN8thwm2TI6+OfKfO7G7BXFhC7jkVUQY+xLqEIhAvGyeZZMO+eswA1Qwo2nioeHd1IhtNyetXsgbkAvvx/aR3KyhKUFAAD33WbggDsOMm/1xQn6yViPYwDRUJtGCMJexf4ut3FxVIU/zQUwLXZdSIpASswgUJUi9LqfeTfB3PG1S8ZyByZ3FwV+WC+36WRWzZu/Thtl5WAOckF7nVY7vZMrauZd+kMFKw0bsv0z8WbHUHuWpgVsCU2f1khtjkgnTxa6jq12o/8alXMkqsqB2RMf1IBEu4e5hI74/b0jDVanWYAabm+FSLUg8MF0Dn3ZSBMtL6jWwzbOe10o9M3cwhNQf8hA9835ACk2FsGapbSi7MRtlHKoNxs0FysmGft36Jy8Z9JgfKKJDEGq7wbz+MmD8ctgqsiX1pEj6vDYudg+m8xTfoD09IDCt9D69ks0fhMf6ryzyvmdbAGVS60svnwcO80Ka6kKiqM7tCAo0RUwKD9jopvWOXNBh88q6rsiG1ydJCFxflyhNqPuPK52gzaf/6DU8VNR7Pc2Way3ead1jhz3Js2AiOXY8DwrdjfgG4uZ9ceNX4pfgv/YE9MMcRyzR3+tbMGaq8=
before_deploy:
- python setup.py build bdist_wheel
deploy:
  - provider: pypi
    user: atal
    skip_cleanup: true
    distributions: "bdist_wheel"
    password:
      secure: "nCWXETP46f8ribAQGIzxEzctddMbdiicLGJywYcefscpFabOnTAu/E4IkiuHPER8SmaIV0mcg9vjN2YGma+2jviG4K+6Owte5r0HLSRuXG1usZFua5JSNxlB+7jl1Yy2+21uYlEOcnNjuSDQJWzQjvgsWcB0JiBnIECWj+lWS5OOcC3tLTMDjVzGrccnfmVJjwyt5SgrIUj2znqSFAdx6zNbYz1ToLhyBo57xkLlKNzRYguPttTqanNSczVutuKu4WnQsRUHq5ZKEIozAeNIAkn38TidAr5VP9ToflIE5/4Cy3P6g8Ocgccmf7vbTyzIGEjDlt9Ag6ZrCybWsf0NfNYXhg9I592TU2SDKPE7+OM9ycoD64TslWBCirslwTmyuv0bG7pbsxW1648bFPFOmN1XkstS3MltCFsUAIrneaEDOYWJeaCtdD2dSrAX797Ql+lwWwcEKmGPSuB3nzghjH2lI0mVg+9pxVLlnacAOmdo8FdIsn/qj7hnIbPKMVXc1TnXeZ2vH7fyLTJM4hcM8kglf50dQ4DVlE40TETDc38DxfOYeQxeMbXRRcStk7iSJXIqJlCX3RSBu+lt+Z3jDcMUk6IlCz79xKlRg9ml3oL6ZhXJeZOZu2/pA/jWy+TX0hHip+H8WzV1m+WbQG4Pbfhmn2MF7c3npLoB9sngdJI="
    on:
      tags: true
      repo: ccpgames/setuphelpers
      condition: $TOXENV = py35
  - provider: releases
    api_key:
      secure: K8YLSt3LC3fCM/QnJx+6tnT2BnRV4wUeuG92Kvl4YF0AtkWqNXaaEXdmgVkd53/18E9/GU323GDEJ5ejoGPGpA6Gz5nN5140ooazkk9Sg4xnPboW0Exn4bbfHij/pn0OVL8AP93JYSOkZkWxKmGdyMQqIS+WnYUHE7a2DLzTVOG/Q8sNOaUWaOiDUKAMDkR6pc2knRnjXa0nDCY3rFrmhC8471CNjw3uyCYAgWqXJkzWHxS1+hBjmAQeOy72eINBLZsShC4pkXB8er1CTgOSIwe2lm/GVQu+bYHfbgH/iA6RidgcfHfYazP1R1f/uhoqcpA72MbzNxi0zJ5pJTyyPaKCQ6U1zWxz6MXAjGvEgzSqDbGNd/h6spsbVtwiYMS58uX4gXtzTlJInPYWWJTuu4LsoT3bxRrhwDrzeY4kRMsNDblYmwvox2+E/iv2tOhCs+eZzQGDlWstEVHDmTTUDQcnGMkuupDHGgoyHX5CK9DE0jeNGvplaLif6XGnFchnDB90w8/8xwQye8PeawBTGqp0qRSA/tIk1BEo98hUrI3XTyWjTfViAFDiYf6JoAmZoFT7NSGq6BWJ52S54g81zrsluiTPCATtNlR8tSs1B4y3MkKfMGg7Hg6Nc1pVbabOLt1hTJFFpQut6YwmkTG3orw8xCWbqTrU6Z+ZUHI3rJo=
    file: "/home/travis/build/ccpgames/setuphelpers/dist/*.whl"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: $TOXENV = py35
